services:
  postgres-db:
    container_name: file-hosting-postgres
    image: postgres:17.2
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: file-hosting-minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - ${MINIO_PORT}:9000
      - ${MINIO_CONSOLE_PORT}:9001
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio_data:/data

  miniomc:
    container_name: file-hosting-miniomc
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_INIT_BUCKET=${MINIO_INIT_BUCKET}
    entrypoint: >
      /bin/sh -c "
      until (mc alias set myminio http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD}) do echo 'Waiting for MinIO...'; sleep 5; done;
      mc mb myminio/$${MINIO_INIT_BUCKET} --ignore-existing;
      mc policy set public myminio/$${MINIO_INIT_BUCKET} || true;
      echo 'MinIO initialization complete';
      tail -f /dev/null
      "

  api:
    container_name: file-hosting-api
    image: file-hosting-api:latest
    env_file:
      - .env
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      SPRING_CONFIG_LOCATION: /config/application.yml
    volumes:
      - ./api/src/main/resources/application.yml:/config/application.yml
      - ./settings.xml.template:/app/settings.xml.template:ro
    depends_on:
      - postgres-db
      - minio
    ports:
      - ${API_PORT}:8080

volumes:
  postgres_data:
  minio_data:
