spring:
  application:
    name: ${app.name} - ${app.version} - ${app.release-stage}

app:
  name: "@project.name@"
  version: "@project.version@"

server:
  error:
    include-message: always

jwt:
  public-secret-key: ${JWT_SECRET}
  token-lifetime: 86400s # 24 часа

minio:
  endpoint: http://${MINIO_HOST}:${MINIO_PORT}
  access-key: ${MINIO_ROOT_USER}
  secret-key: ${MINIO_ROOT_PASSWORD}